name: Upload and Deploy Files

on:
  push:
    paths:
      - 'AU/**'
      - 'CAD/**'
      - 'GGA/**'
      - 'NDA/**'
      - 'US/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find and Deploy Files
      run: |
        for file in $(find . -type f -name '*' -path '*/AU/*' -o -path '*/CAD/*' -o -path '*/GGA/*' -o -path '*/NDA/*' -o -path '*/US/*' -o -path '*/US/*'); do
          folder=$(basename "$(dirname "$file")")
          filename=$(basename "$file")
          
          if [ "$folder" == "$filename" ]; then
            echo "Uploading $filename to Tomcat server: $folder"
          fi
        done
