name: Upload and Deploy Files

on:
  push:
    paths:
      - 'AU/**'
      - 'CAD/**'
      - 'GGA/**'
      - 'NDA/**'
      - 'US/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find and Deploy Files
      run: |
        for file in $(find . -type f \( -path '*/AU/*' -o -path '*/CAD/*' -o -path '*/GGA/*' -o -path '*/NDA/*' -o -path '*/US/*' \)); do
          folder=$(basename "$(dirname "$file")")
          filename=$(basename "$file")
          
          # Remove the file extension from the filename
          filename_no_ext="${filename%.*}"

          if [ "$folder" == "$filename_no_ext" ]; then
            echo "Uploading $filename to Tomcat server in folder: $folder"
          fi
        done
